# Generated by Django 5.1.4 on 2024-12-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
    ]
