# Generated by Django 5.1.4 on 2024-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_user_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('HOD', 'HOD'), ('Principal', 'Principal'), ('Admin', 'Admin')], max_length=100),
        ),
    ]
