# Generated by Django 5.1.4 on 2024-12-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_patient_ward_alter_staff_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.hospital'),
        ),
    ]
