# Generated by Django 5.1.4 on 2024-12-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_staff_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ward',
            field=models.CharField(max_length=30),
        ),
    ]
