# Generated by Django 5.1.4 on 2024-12-07 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_staff_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
    ]
