# Generated by Django 5.1.4 on 2024-12-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='mainapp.staff'),
        ),
    ]
