# Generated by Django 5.1.4 on 2024-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_patient_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge',
            field=models.DateTimeField(null=True),
        ),
    ]
