# Generated by Django 5.1.4 on 2024-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_patient_admit_alter_patient_discharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='SOS',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
